### ISSUE TITLE
Revert to MySQL rather than using MariaDB

### ISSUE THREAD

**Issue by Steve-Palmer** [opencdms/Climsoft#193]
Can we revert to using MySQL instead of MariaDB?  
Advantages: this will reduce the perceived complexity of installing the new software and will allow database administrators to use their existing MySQL installations. Sites with existing medium Climsoft V3.2 installations currently use MySQL for the background database. It may simplify the transition of data from V3.2 to V4.x installations. The roadmap for Climsoft V5 involves changing to PostgreSQL to take advantage of better support for areal data, so MariaDB is not a long-term requirement.
Disadvantage: My understanding is that there is no difference in the functionality currently used by Climsoft V4. If this is wrong, the work to implement may involve code changes as well as changing the database link.

**Comment by mhabimana** [comment]
Thanks Steve to raise this issue.
Following the above article about both MariaDB and MySQL Pros and Cons: https://www.quora.com/What-are-the-pros-and-cons-of-MariaDB-versus-MySQL-database, which shows that the future of MariaDB is uncertain. It is developed mainly by a small company that may not have as strong a future as Oracle. I support your idea of revert back to MySQL because of the sustainability of MySQL and the  justifications in your comment.

**Comment by smachua** [comment]
Hi All,
Although reverting to Mysql may make thing looks simpler there are some other factors to consider. We found MariaDB having more improved functionalities on security. CLIMSOFT V4 code heavily uses those functions. In V3.2 security functionalities were handled through the ACCESS workgroup file that was found a bit troublesome. I therefore need first to test whether the implemented V4 code on users and database security is compatible with Mysql.
Kind regards
Samuel 

    On Monday, May 15, 2017 12:18 PM, Steve Palmer <notifications@github.com> wrote:
 

 Can we revert to using MySQL instead of MariaDB?
Advantages: this will reduce the perceived complexity of installing the new software and will allow database administrators to use their existing MySQL installations. Sites with existing medium Climsoft V3.2 installations currently use MySQL for the background database. It may simplify the transition of data from V3.2 to V4.x installations. The roadmap for Climsoft V5 involves changing to PostgreSQL to take advantage of better support for areal data, so MariaDB is not a long-term requirement.
Disadvantage: My understanding is that there is no difference in the functionality currently used by Climsoft V4. If this is wrong, the work to implement may involve code changes as well as changing the database link.—

**Comment by isedwards** [comment]
_MariaDB advantages_
- I think the MariaDB software is here to stay and that it may start to replace MySQL in the future [1]
- MariaDB is currently a slightly better fit for Climsoft technically, although most of the Climsoft code will work perfectly with MySQL instead

_MariaDB disadvantages_
- I agree that MariaDB's position is still a bit uncertain (MySQL still has the web-database niche, and PostgreSQL tends to be the standard open source replacement for Oracle DB)
- Climsoft users would need to change database technology and they may feel they need additional training etc.

For me, the biggest motivating factor to stay with MySQL at this time is Steve's point about the strong likelihood that we will move to PostgreSQL in version 5. This is the database software that is generally replacing Oracle DB in met services and is also the most likely candidate for OpenCDMS.  If we ask users to move from MySQL to MariaDB and then to something else in the future it would be very messy.

I'm in favour of staying with MySQL for version 4.x if possible and working around the technical issues due to losing the new MariaDB features.

[1] https://mariadb.com/about-us/newsroom/press-releases/mariadb-positioned-leader-its-gartner-magic-quadrant-debut

**Comment by isedwards** [comment]
At this time, MariaDB has several new features over MySQL [1]

Of these, I believe we are only dependent on the new "ROLES" capability.

    A role bundles a number of privileges together. It assists larger organizations where,
    typically, a number of users would have the same privileges, and, previously, the only
    way to change the privileges for a group of users was by changing each user's privileges
    individually.[2]

With MariaDB, multiple users can be assigned the same ROLE, we can then change the privileges for all of them just by updating the ROLE.  We can also be sure that each person has the correct privileges just by checking their ROLES.

To achieve the same in MySQL we need to:
a) Maintain our own record in the Climsoft database of which roles each user has (instead of asking MariaDB for the set of ROLES that they are assigned)
b) Modify any existing routines that we have written in the VB code to record the user's roles in our own "roles table" instead of using and relying on MariaDB ROLES.
c) If the privileges for a particular role change then we need a new routine to also update the privileges for each existing user who is a member of the role
d) Ensure that when we assign a role to a user in the future the correct set of privileges for that role are granted

We are actually already doing a & b. We are keeping our own record of roles in a database table called `climsoftusers` which has the following definition:
```
CREATE TABLE `climsoftusers` (
	`userName` VARCHAR(50) NOT NULL,
	`userRole` VARCHAR(50) NOT NULL,
	PRIMARY KEY (`userName`)
)
```

@smachua - does this all sound correct?

[1] https://web.archive.org/web/20170130082209/https://mariadb.com/kb/en/mariadb/mariadb-vs-mysql-features#extensions-entityampentity-new-features
[2] https://mariadb.com/kb/en/mariadb/roles_overview/

**Comment by isedwards** [comment]
**Suggested implementation**

The [MariaDB ROLE statement](https://mariadb.com/kb/en/mariadb/set-default-role/) is [repeated twice](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself), occuring in two places in the code:
1. [frmUserManagement.vb#L74-L78](https://github.com/opencdms/Climsoft/blob/7f44a09da5985ca2da0d95c901c266074ceb2d1d/ClimsoftVer4/ClimsoftVer4/frmUserManagement.vb#L74-L78)
2. [frmUsers.vb#L68-L72](https://github.com/opencdms/Climsoft/blob/7f44a09da5985ca2da0d95c901c266074ceb2d1d/ClimsoftVer4/ClimsoftVer4/frmUsers.vb#L68-L72)

Both examples make use of the following SQL:

`SET DEFAULT ROLE " & cboUserType.Text & " FOR '" & txtUserName.Text & "'@'localhost';`

In *frmUserManagement* [(1)](https://github.com/opencdms/Climsoft/blob/7f44a09da5985ca2da0d95c901c266074ceb2d1d/ClimsoftVer4/ClimsoftVer4/frmUserManagement.vb#L74-L78) the code is currently commented.

In order to make the current code work with MySQL, the code in *frmUsers* [(2)](https://github.com/opencdms/Climsoft/blob/7f44a09da5985ca2da0d95c901c266074ceb2d1d/ClimsoftVer4/ClimsoftVer4/frmUsers.vb#L68-L72) could also be commented. It appears that this will not break anything because we are currently not reading ROLE information back from MariaDB after it has been set. In *frmUserManagement* the ROLES section is probably commented because this section of the code is instead making extensive used the old-style granting of privileges on a per user basis, e.g. [frmUserManagement.vb#L87-L1306](https://github.com/opencdms/Climsoft/blob/7f44a09da5985ca2da0d95c901c266074ceb2d1d/ClimsoftVer4/ClimsoftVer4/frmUserManagement.vb#L87-L1306) (this is compatible with MySQL and is not using the MariaDB ROLES capability).

There are other places in the code where we work with roles, but these are all implemented in our own `climsoftusers` table, and therefore work with either MySQL or MariaDB. Examples include:

1. In the SynopRA1 key entry form we delare global variables that are accessible across the whole project. These are a dataset (ds) and a data adapter (da) called `dsClimsoftUsersRoles` and `daClimsoftUsersRoles`. These are used in some (but not all) places when working with the `climsoftusers` database table [formSynopRA1.vb#L28-L29](https://github.com/opencdms/Climsoft/blob/7f44a09da5985ca2da0d95c901c266074ceb2d1d/ClimsoftVer4/ClimsoftVer4/formSynopRA1.vb#L28-L29)

2. In the login screen code we fill the `dsClimsoftUserRoles` dataset with a copy of the current contents of the `climsoftusers` database table [frmLogin.vb#L85-L96](https://github.com/opencdms/Climsoft/blob/7f44a09da5985ca2da0d95c901c266074ceb2d1d/ClimsoftVer4/ClimsoftVer4/frmLogin.vb#L85-L96). This is then used in the main menu form to control which sections of the interface are accessible based on the roles that the logged in user has [frmMainMenu.vb#L26-L100](https://github.com/opencdms/Climsoft/blob/7f44a09da5985ca2da0d95c901c266074ceb2d1d/ClimsoftVer4/ClimsoftVer4/frmMainMenu.vb#L26-L100)

**Comment by mhabimana** [comment]
Most of the code in Climsoft uses the mariadb_climsoft_db_v4 database (that is specified in the config.inf file).  However, the code in frmUserManagement.vb all references a different database:
    Sql = "GRANT SELECT ON mariadb_climsoft_test_db_v4.observationfinal TO '" & txtUserName.Text & "';"

**Comment by isedwards** [comment]
@mhabimana's changes look good to me. The `mariadb_climsoft_db_v4` and `mariadb_climsoft_test_db_v4` MariaDB databases can also be successfully imported into MySQL.
