### ISSUE TITLE
Creation of the Installer using the Advanced Installer Open Source tool

### ISSUE THREAD

**Issue by mhabimana** [opencdms/Climsoft#234]
Ian is working on the climsoft installer using the Advanced Installer Open Source tool ,this will be then compared to the one created using Inno-Setup.

**Comment by Fortunata** [comment]
It will be good if the installer shortens the process of security configuration but remember such security controls are required in the database management systems

**Comment by mhabimana** [comment]
@isedwards - Any progress on this?

**Comment by isedwards** [comment]
I've completed a proof of concept. It's currently online here: https://github.com/opencdms/climsoft-installer.

The demonstration application shows that it is possible to automate the install of the initial Climsoft database and test database from within VB.NET (instead of the user having to undertake the steps manually).  I'll get on with adding this to Climsoft over the next week.

**Comment by mhabimana** [comment]
@isedwards -Thanks for the update

**Comment by isedwards** [comment]
This issue has the following parts:
- [ ] Comparing the setup programs generated by InnoSetup and Advanced Installer
- [ ] Deciding whether additional software like WRPlot should be bundled in the installer, or installed separately and used by Climsoft if it is detected as having been installed
- [ ] Moving the creation of databases from being a manual task to something that is done for you by the main software.  This will also allow us to manage updates ("migrations") to the database automatically
