### ISSUE TITLE
CLimsoft V4 Hourly wind 

### ISSUE THREAD

**Issue by Fortunata** [opencdms/Climsoft#253]
Issues encountered when working with hourly wind form (issue raised in the attached document) for consideration
[CLIMSOFT V4 Hourly Wind.docx](https://github.com/opencdms/Climsoft/files/1469865/CLIMSOFT.V4.Hourly.Wind.docx)

**Comment by mhabimana** [comment]
@Fortunata -Thank you for the above issue.For the point issue raised on point1,the reason why the text box on the form is not active is because this can not be changed by any user unless the user with the right permission and this is set under tool/General settings as shown the interface below.The rest of the points raised @smachua  will be able to respond:
![image](https://user-images.githubusercontent.com/10340170/32768407-c14f2ba2-c928-11e7-8cfb-04d4b6e1b0cc.png)

**Comment by Fortunata** [comment]
Thanks am going to try it and see
