### ISSUE TITLE
Export of data from CLIMSOFT

### ISSUE THREAD

**Issue by rdstern** [opencdms/Climsoft#258]
This may be a redundant aspect, because the issue is on Version 3.2, so it may be different already in Version 4.

We were exporting data from CLIMSOFT in lesotho.  We repeatedly ran into the limit of 1 million records, because Version 3.2 only exports to Excel.  Perhaps there are other possibilities, (even in Version 3.2) but we couldn't find them.

In addition it doesn't inform you about the limit.  It just exports what it can and then leaves the rest.  We have to detect the limit, because we are then missing some data.  This will be a more common issue in larger countries.

I assume Version 4 is able to export in a variety of formats as well as Excel?  And hence the 1 million limit no longer exists?

Thanks

**Comment by mhabimana** [comment]
@rdstern - Thanks for raising this issue. However, Climsoft version 3.2 and 4 export data in CSV (Comma Separated Value) by default but you can decide to save the file as Excel or leave it in csv and I think the best way is to leave the file in csv to avoid row limitation,I am not sure if csv file has got a number of row limit.  I totally agree with you that we need to explore the option of including other variety of format in V4.

**Comment by smachua** [comment]
@rdstern - Climsoft v 3.2 and even v 4 exports data in text (csv) files but not in excel. Although csv file can be opened through many applications by default it will be open in excel. We have not experienced a limit in number of records that Climsoft can output into a text(csv) file. It is worth finding out whether the limitation in records displayed was due to the version of excel used.

**Comment by isedwards** [comment]
I agree that this certainly sounds like the Excel row limit issue (see [here](https://support.office.com/en-gb/article/Excel-specifications-and-limits-1672b34d-7043-467e-8e27-269d656771c3)). The old Excel versions used to just throw away the data silently. The new versions should give you a warning that the data will be lost the first time you save as an Excel file instead of CSV file.

@rdstern - are you able to read all of the data using superior software to Excel (e.g. R-Instat......)
