### ISSUE TITLE
Populate required elements in the list box

### ISSUE THREAD

**Issue by mhabimana** [opencdms/Climsoft#312]
@Patowhiz @maxwellfundi @isedwards : We are moving slowly and yet the testing of the entire system should start next week. Can you please finalise the remaining issues on the data entry forms this week so that the testing start next week? These are: the upload data progress dialog on all the data entry forms,the issue of the AddNew button on form Monthly,the form Synoptic_2_ra1 ( the following months:Sept to Dec are not active). 
However,there is an option to select required elements to populate in the element list box of the data entry forms instead of populating the entire list in the list box which are more than 400 elements using the dialog below (there is a field in the table obselement called selected to restrict this( 1 is to select and 0 is to deselect element):
![image](https://user-images.githubusercontent.com/10340170/43768391-eaa8a9ea-9a3f-11e8-9033-448ae92dba0f.png)

Only selected elements should appear in the data entry forms elements list box. This is not working as desired at the moment.

**Comment by Patowhiz** [comment]
@mhabimana I was not aware of the selection option. I'll add this in the new pull request

**Comment by mhabimana** [comment]
@Patowhiz Thanks and noted. I see,you are right,the form synop_2_ra1 is OK, I did not change the year.Future dates should not be active.

**Comment by Patowhiz** [comment]
@mhabimana for clarity. My interpretation is, the element selector will load only the elements that have been indicated as selectable. That means when someone fails to see the element he is looking for he will have to go back to the metadata and set it as selected. And this will happen for the forms that have this control.

**Comment by mhabimana** [comment]
Thanks, you are right

**Comment by Patowhiz** [comment]
@mhabimana the issue of formMonthly not going to a new record when you click on button add new is because of the sequencer. frmMonthly uses table seq_year for sequencing. That means it only tries to go to the next year since its the only column used. With our new implementation of not allowing future date entry it cannot go to 2019.

However this does not limit the user from entering new records. By changing the element or the station, the form automatically knows it's a new record if it does not exist. I'm open to suggestion on how this can be implemented differently

![seq_year](https://user-images.githubusercontent.com/21179007/43827170-e0ae3848-9b01-11e8-9212-9a73b0f7a60d.JPG)

**Comment by mhabimana** [comment]
@Patowhiz Thanks I get your point. But I am not sure if the year sequencer is working well since AddNew  is not creating the empty form with the next year as it is supposed to do.

**Comment by mhabimana** [comment]
@Patowhiz @maxwellfundi @isedwards @smachua Now we have the new data entry forms ready. Well done. I would suggest now that @smachua clone the latest copy of the project and add the remaining features (Double Key Entry and Data Gaps).
