### ISSUE TITLE
Populating Missing Value Flag in Observationinitial

### ISSUE THREAD

**Issue by mhabimana** [opencdms/Climsoft#322]
@maxwellfundi @Patowhiz I have realised that the missing values (M) is not being stored in the database (observationinitial) when uploading data from the data entry forms to observationinitial but rather the date associated with the missing value is being skipped in observationinitial database table . We need to rectify this since the dates corresponding to missing values should appear in the database with the column(field) of obsValue  **empty** and the column of Flag should contains **M**.

**Comment by Fortunata** [comment]
On this issue of missing data , What happened to the inventory as a meta data product showing which data is available and missing par station par months . This can be output as an excel sheet. This is to Marcellino

**Comment by Patowhiz** [comment]
@mhabimana I had implemented this based on Samuel previous functionality. He was skipping empty values. To be clear, you are saying we should have empty values with flag M be store? What about empty values without a flag?

**Comment by mhabimana** [comment]
@Patowhiz Thanks. This is how it is supposed to work. Empty value automatically gives M (missing) and should be stored in the observationinitial under Flag field. Yes,I discover the same issue as well in what Samuel did but we need to correct this. @smachua I am not sure if you have made any correction in your latest PR.

**Comment by Patowhiz** [comment]
@mhabimana what about the empty values without a flag. Remember M is only assigned when you press "enter".

**Comment by Patowhiz** [comment]
@mhabimana  I'm implementing this in a way that. any missing values will be uploaded to the observation initial, whether it has a flag or not. Is that okay with you?

**Comment by mhabimana** [comment]
@Patowhiz OK, I just had discussion with Samuel on this and we agree to leave it like this,in this case,if someone want to check missing values,he will be able to see these in the data entry forms.

**Comment by Patowhiz** [comment]
So I should not change anything on this?

**Comment by mhabimana** [comment]
@smachua Can you help us on this?

**Comment by mhabimana** [comment]
@Patowhiz The PR #302  creates many conflicts,I am going to close this. @smachua is going to commit a new PR and then we will see how to continue from there. I suggest we hold on a bit.

**Comment by mhabimana** [comment]
@Patowhiz I get your point. M if applied when the enter key is pressed and if not, the text box remains empty after saving and there is no flag associated with this. But the idea is that any empty text box in the data entry form should be associated with the Flag M,whether this was done by error or not.  I think @smachua  need to shed more light on this and make sure we are implementing the right functionality.

**Comment by Patowhiz** [comment]
Yeah. Because, I thought having no value and no flag could mean the value was not recorded, not necessarily missing. I would recommend storing the value whether empty or not,whether it has a flag or not in the observation initial, though I still don't know the absolute purpose for the observation initial. I'm open to any kind of implementation

**Comment by smachua** [comment]
@Patowhiz et al. When saving at key entry forms all text boxes without values will be treated as missing and should be given a flag "M". Actually missing data means observations that could not be determined. Although users are required to press ENTER key on the affected text boxes there is a likelihood of some failing to do that. In cases where the missing observations are later located the key entry forms are updated by entering that value and uploading the forms again.
It is not very necessary to upload the missing records to "initial" because of the complexity of updating the missing data that is later located. The main purpose of "initial" is facilitate the QC operations.

**Comment by Patowhiz** [comment]
@smachua  @mhabimana  Okay, how do we proceed, should we implement this or leave it as it is?
For the sake of clarity, if we are to implement this , it means  during the upload, empty values will always be uploaded with "M" set as the flag regardless of whether the flag is there or not.

**Comment by smachua** [comment]
@Patowhiz I suggest you leave it the way it is. I will open a discussion on handling of missing values (M) so that others can give their views as well.
