### ISSUE TITLE
Configure general settings - section 4.2

### ISSUE THREAD

**Issue by rdstern** [opencdms/Climsoft#330]
I was not able to see what I should change here.  There is a rather strict statement in Section 4.2 that says:

IMPORTANT!
In Figure 10a, the Administrator must navigate through all the records in the dialog and change the contents in the text box to the right of the label “Setting Value” to suit the required local configuration.

What should we be doing here?

**Comment by mhabimana** [comment]
@rdstern The general settings dialog below contains default settings and users are advised to adjust according to their country:
E.g1. In some countries wind direction is recorded in **3** digits and others in **2** digits). 
E.g2. The default path where to store the QC report file(s) is set to this path C**:\data\QC** but users can decide to change this path the way they want or leave this the way it is. Ideally, after changing the setting value elements(text box),you need to click on the command button update so that the change(s) may take effect. Hope this makes sense.
![image](https://user-images.githubusercontent.com/10340170/44664551-43e9c480-aa1c-11e8-8be0-886ff4f09020.png)
The same dialog in table view mode:
![image](https://user-images.githubusercontent.com/10340170/44664032-c5405780-aa1a-11e8-9089-62bb1552384b.png)
