### ISSUE TITLE
Data entry problem

### ISSUE THREAD

**Issue by rdstern** [opencdms/Climsoft#350]
In the data entry forms, when I click on the first option, namely form synoptic, I get this nasty message:

![image](https://user-images.githubusercontent.com/11226469/44808756-bce04c00-abd5-11e8-8bce-847b80bffccb.png)

If you click Continue then it loads the data entry form.

But this is a bug on the new data entry forms that should be fixed before Rwanda.

**Comment by mhabimana** [comment]
@rdstern You are right. This a bug,there are some 3 flags which are not necessary in the EF,these where removed in the Database schema but there still present in the EF and need to be removed. This issue was addressed in the Beta2 PR which is pending awaiting for merging. When I shares the installer mentioned some few issue(bugs) which I was expecting to be there,this is one of these.

**Comment by rdstern** [comment]
Thanks.  I am keen that any bugs are noted also as issues, both so they are clear to everyone, and to point to what should be tested, once the solutions have been merged./

Would you be able to write an issue on each of the other bugs that are waiting to be merged?

**Comment by mhabimana** [comment]
@rdstern Thanks,Will do that.

**Comment by mhabimana** [comment]
@smachua @isedwards I am still seing the above error mentioned by @rdstern even after merging beta2 with the master. Kindly check what is going wrong on this form (form synop a1).
