### ISSUE TITLE
Testing Climsoft Version 4 Database on Linux Environment

### ISSUE THREAD

**Issue by mhabimana** [opencdms/Climsoft#438]
Climsoft has been thoroughly tested on Windows PCs and Windows Server but not yet on Linux environment. Climsoft application is available for Windows systems and not for Linux but the database is flexible and can be installed on both Windows and Linux servers to unable the interaction between Clients PCs with Windows O.S and Server ( with either  Linux or Windows O.S). A thorough testing on Linux  environment server is required to be able to support users with Linux server systems.

**Comment by mhabimana** [comment]
@isedwards Thanks.I think instructions will be very helpful.I guest the same instructions will be applied to different Linux O.S.

**Comment by smachua** [comment]
@isedwards it's a good idea to have a guide on how to setup climsoft database in a Linux server. It can as well be included in the users manual. We once tried running Climsoft database in MySQL in the Linux sever at ICPAC, Nairobi and worked ok. Someone else interested in doing the same will find the guide helpful.

**Comment by isedwards** [comment]
@mhabimana do you know whether any one has tried this, but it has not worked for them?

**Comment by isedwards** [comment]
If they try it, it should just work (it's not really any different to connecting to a database on a separate Windows machine).

I looked for official installation guides, there's the official MySQL one here:

https://dev.mysql.com/doc/refman/8.0/en/linux-installation.html

Or, a better approach might be to follow the official guide for the version of Linux there're using, e.g.

https://help.ubuntu.com/lts/serverguide/mysql.html.en

BUT, often there are better guides written by other people.

**Comment by mhabimana** [comment]
@isedwards I have used Linux Ubuntu and the installation is straight forward but the issue is to access the server through the client pc running on windows and to be able to access the DB remotely via a user friendly database GUI client like HeidiSQL.

**Comment by isedwards** [comment]
But, once the database is available via an IP address and port number over a network, or over the internet, it no longer matters whether the server is Linux or Windows

**Comment by Steve-Palmer** [comment]
What is the function of the database GUI client (HeidiSQL or similar)? Climsoft itself acts as the client for its own interactions with the database. Perhaps the additional GUI is only needed for managing backups and partitioning or other manipulation which is required to manage the database itself, rather than managing the data within the database. I would accept that use case. I would also accept that other GUI clients should have read-only access to the data in the database becuse there could be justification to add other tools which read the data for their own purposes. However I am strongly against adding other client tools which have write access to the data in the database, because at that point, we can no longer ensure that the data in the database has good provenance (i.e. someone may have altered data without proper authority).

**Comment by mhabimana** [comment]
@Steve-Palmer You are right. Climsoft itself acts as the client for its own interactions with the database. We are not adding any new tool. All the management will be done at the application level (Climsoft). HeidiSQL or similar database GUI is important at the initial stage,during the installation,configuration and by the expert who knows what he/she is doing,this is the back-end of the system and users are given permissions to the front-end and not to the back-end. Hope this makes sense.

**Comment by mhabimana** [comment]
This was tested and the result was good.It can now be closed.

**Comment by isedwards** [comment]
@mhabimana - is it possible to put your instructions for installing MySQL on Linux on the Climsoft wiki and then add a link from here?

**Comment by mhabimana** [comment]
@isedwards :Noted.

**Comment by mhabimana** [comment]
@isedwards : Here is the Link: Climsoft Database Configuration on LINUX (MySQL or MariaDB Server)

**Comment by isedwards** [comment]
Excellent!  Thank you Marcellin!
