### ISSUE TITLE
Linux

### ISSUE THREAD

**Issue by mhabimana** [opencdms/Climsoft#494]
1.
![1](https://user-images.githubusercontent.com/10340170/55085818-5a422680-50b8-11e9-8d5c-ab0dac3ae4f4.png)

2.
![image](https://user-images.githubusercontent.com/10340170/55085957-9aa1a480-50b8-11e9-95c0-a64dbb19ecf9.png)

**Comment by isedwards** [comment]
@mhabimana instead of uploading the images as part of an issue and then closing the issue, I tend to add them into the `wiki` folder in this repository: https://github.com/opencdms/climsoft.org

I've reopened this issue so that we can add these new images with the others.

I can do this in the next few days or I'm happy if you want to have a go?

**Comment by mhabimana** [comment]
@isedwards : Thanks,correction applied.This can now be closed.
