### ISSUE TITLE
Backup on client PC

### ISSUE THREAD

**Issue by murenziherve** [opencdms/Climsoft#554]
Hello all, i am not able to perform backup of data using client PC. i got the error message below showing the issue of path.
![image](https://user-images.githubusercontent.com/53932131/62775560-4962e200-baa8-11e9-8cbf-03dd5a227bdb.png)

**Comment by smachua** [comment]
@murenziherve select a valid folder in the server where backup files will be saved.

**Comment by murenziherve** [comment]
@smachua -Thanks,I want this to be on the Client PC(local machine) because I don't have access to the server.

**Comment by Patowhiz** [comment]
@murenziherve did you create the directory(folder) as stated by @smachua ?

**Comment by mhabimana** [comment]
@Patowhiz -Thanks, for the Server-Clients architecture, the current settings is that the **QC** be done at the Client level but the **data backup** at the server. However @smachua said that it is possible to do this operation at the Client level but since this is a sensible operation which can expose the entire data in the database to external users, it is good to leave this operation be done at the server side only.

**Comment by Patowhiz** [comment]
That's reasonable. So currently the backup happens on the same server but in a different chosen directory? From which the user can manually copy to an external device?
